/********************************** (C) COPYRIGHT *******************************
 * File Name          : main_v3f.c
 * Author             : WCH
 * Version            : V1.0.0
 * Date               : 2025/03/01
 * Description        : Main program body for V3F.
 *********************************************************************************
 * Copyright (c) 2025 Nanjing Qinheng Microelectronics Co., Ltd.
 * Attention: This software (modified or not) and binary are used for
 * microcontroller manufactured by Nanjing Qinheng Microelectronics.
 *******************************************************************************/

/*
 *@Note
 LTDC routine:

 This example shows how to use LTDC driver to display some animations on the LCD.
 The animation was generated by a simple C code, show the basic usage of LTDC driver.
     Hardware connection:
		PF1 -- LTDC_CLK 
		PC6 -- LTDC_HSYNC 
		PA7 -- LTDC_VSYNC 
		PC5 -- LTDC_DE 
		PE1 -- LTDC_R[0] 
		PF0 -- LTDC_R[1] 
		PD13 -- LTDC_R[2] 
		PD12 -- LTDC_R[3] 
		PD11 -- LTDC_R[4] 
		PA9 -- LTDC_R[5] 
		PA8 -- LTDC_R[6] 
		PC4 -- LTDC_R[7] 
		PE5 -- LTDC_G[0] 
		PE6 -- LTDC_G[1] 
		PA6 -- LTDC_G[2] 
		PC9 -- LTDC_G[3] 
		PC8 -- LTDC_G[4] 
		PC1 -- LTDC_G[5] 
		PC7 -- LTDC_G[6] 
		PD3 -- LTDC_G[7] 
		PE4 -- LTDC_B[0] 
		PE0 -- LTDC_B[1] 
		PD6 -- LTDC_B[2] 
		PD7 -- LTDC_B[3] 
		PD4 -- LTDC_B[4] 
		PD5 -- LTDC_B[5] 
		PA14 -- LTDC_B[6] 
		PD2 -- LTDC_B[7] 
		PB12 -- LTDC_BL


*/

#include "debug.h"
#include "hardware.h"

/* Global define */

/* Global Variable */

/*********************************************************************
 * @fn      main
 *
 * @brief   Main program.
 *
 * @return  none
 */
int main(void)
{
	SystemInit();
	SystemAndCoreClockUpdate();
	Delay_Init();
	USART_Printf_Init(115200);
	Delay_Ms(1000);

	printf("SystemClk:%d\r\n", SystemClock);
	printf("V3F SystemCoreClk:%d\r\n", SystemCoreClock);
	Delay_Ms(500);

#if (Run_Core == Run_Core_V3FandV5F)
	NVIC_WakeUp_V5F(Core_V5F_StartAddr);//wake up V5
	HSEM_ITConfig(HSEM_ID0, ENABLE);
    NVIC->SCTLR |= 1<<4;
	RCC_HB1PeriphClockCmd(RCC_HB1Periph_PWR,ENABLE);
	PWR_EnterSTOPMode(PWR_Regulator_ON, PWR_STOPEntry_WFE);
	HSEM_ClearFlag(HSEM_ID0);
	printf("V3F wake up\r\n");

	Hardware();

#elif (Run_Core == Run_Core_V3F)
	
	Hardware();

#elif (Run_Core == Run_Core_V5F)
	NVIC_WakeUp_V5F(Core_V5F_StartAddr);//wake up V5
	PWR_EnterSTOPMode(PWR_Regulator_ON, PWR_STOPEntry_WFE);
	printf("V3F wake up\r\n");
#endif

	
    while(1)
    {

    }
}
